TRANSLATIONS = {
    'EN': {
        'title': "🧬 Human Genome Analysis",
        'subtitle': "_Explore and analyze DNA sequences with advanced bioinformatics tools._",
        'sidebar_header': "🔍 Gene Selection",
        'search_method': "Search Method",
        'search_by_name': "Search by Name",
        'accession_id': "Accession ID",
        'gene_name_placeholder': "e.g. Insulin, TP53",
        'results': "Results",
        'no_matches': "No matches found.",
        'metadata_error': "Metadata not available.",
        'settings_header': "⚙️ Analysis Settings",
        'kmer_len': "K-mer Length",
        'window_size': "Rolling Window (bp)",
        'analyze_btn': "🚀 Analyze Sequence",
        'fetching': "Fetching sequence data for",
        'loaded': "Loaded",
        'description': "Description",
        'raw_seq': "Raw Sequence (First 500bp)",
        'tab_overview': "📊 Overview",
        'tab_dna': "🧬 DNA Structure",
        'tab_kmers': "🦠 K-mers",
        'tab_protein': "🥩 Protein Analysis",
        'tab_advanced': "🔎 Motifs & Entropy",
        'tab_ai': "💬 AI Assistant",
        'tab_disease': "🏥 Disease Associations",
        'ai_intro': "Chat with the AI Gene Assistant to learn more about this gene.",
        'ai_placeholder': "Ask about function, disease, or mechanism...",
        'ai_welcome': "Hello! I am your AI Gene Assistant. Ask me anything about this gene!",
        'allele_freq': "Allele Frequency (1000 Genomes)",
        'pop_afr': "African",
        'pop_amr': "Admixed American",
        'pop_eas': "East Asian",
        'pop_eur': "European",
        'pop_sas': "South Asian",
        'tab_3d': "🧬 3D Structure",
        'tab_mutation': "🧪 Mutation Lab",
        'tab_align': "⚔️ Alignment",
        'pdb_input': "PDB ID (e.g. 1TRZ)",
        'render_3d': "Render 3D Structure",
        'mutation_intro': "Edit the DNA sequence below to simulate mutations.",
        'simulate_btn': "Run Simulation",
        'original': "Original",
        'mutated': "Mutated",
        'protein_diff': "Protein Differences",
        'silent_mutation': "Silent Mutation (No protein change)",
        'stop_codon': "⚠️ Stop Codon Introduced!",
        'align_intro': "Compare two sequences to find similarities and mutations.",
        'seq1': "Sequence 1 (Reference)",
        'seq2': "Sequence 2 (Query)",
        'align_btn': "Align Sequences",
        'alignment_score': "Alignment Score",
        'match_score': "Match Score",
        'mismatch_score': "Mismatch Score",
        'gap_score': "Gap Score",
        'seq_len': "Sequence Length",
        'gc_content': "GC Content",
        'base_comp': "Base Composition",
        'gc_skew': "GC Skew Analysis",
        'gc_skew_desc': "Rolling GC Skew to identify replication origins or biases.",
        'codon_usage': "Codon Usage Bias",
        'codon_table': "View Codon Usage Table",
        'kmer_freq': "-mer Frequency Analysis",
        'no_kmers': "No K-mers found.",
        'trans_props': "Translation & Physicochemical Properties",
        'prot_seq': "Protein Sequence",
        'mol_weight': "Mol. Weight",
        'isoelectric': "Isoelectric Pt (pI)",
        'instability': "Instability Idx",
        'aromaticity': "Aromaticity",
        'unstable': "⚠️ Protein is classified as **unstable** (Index > 40).",
        'stable': "✅ Protein is classified as **stable**.",
        'entropy': "Entropy Analysis",
        'global_entropy': "Global Shannon Entropy",
        'calc_rolling': "Calculate Rolling Entropy",
        'motif_search': "Motif Search",
        'find_motif': "Find Motif (DNA)",
        'found_matches': "Found {} matches.",
        'not_found': "Not found.",
        'error_fetch': "Could not fetch data for ID:",
        'landing_info': "👈 Please select a gene or enter an Accession ID in the sidebar to start.",
        'features_title': "### Features",
        'features_list': """
        - **Protein Analysis**: Molecular weight, pI, and stability prediction.
        - **DNA Structure**: GC Skew visualization for detecting replication origins.
        - **Interactive Plots**: Zoomable charts for K-mers and entropy.
        """,
        'language_select': "Language",
        'disease_map': "Disease Variant Map",
        'disease_desc': "Known pathogenic variants mapped to the reference sequence (Educational).",
        'variant': "Variant",
        'disease': "Disease",
        'significance': "Significance",
        'position': "Position"
    },
    'IT': {
        'title': "🧬 Analisi Genoma Umano",
        'subtitle': "_Esplora e analizza sequenze di DNA con strumenti bioinformatici avanzati._",
        'sidebar_header': "🔍 Selezione Gene",
        'search_method': "Metodo di Ricerca",
        'search_by_name': "Cerca per Nome",
        'accession_id': "ID Accessione",
        'gene_name_placeholder': "es. Insulina, TP53",
        'results': "Risultati",
        'no_matches': "Nessuna corrispondenza trovata.",
        'metadata_error': "Metadati non disponibili.",
        'settings_header': "⚙️ Impostazioni Analisi",
        'kmer_len': "Lunghezza K-mer",
        'window_size': "Finestra Mobile (pb)",
        'analyze_btn': "🚀 Analizza Sequenza",
        'fetching': "Recupero dati sequenza per",
        'loaded': "Caricato",
        'description': "Descrizione",
        'raw_seq': "Sequenza Grezza (Primi 500pb)",
        'tab_overview': "📊 Panoramica",
        'tab_dna': "🧬 Struttura DNA",
        'tab_kmers': "🦠 K-mers",
        'tab_protein': "🥩 Analisi Proteica",
        'tab_advanced': "🔎 Motivi & Entropia",
        'tab_ai': "💬 Assistente AI",
        'tab_disease': "🏥 Associazioni Malattie",
        'ai_intro': "Chatta con l'Assistente AI per saperne di più su questo gene.",
        'ai_placeholder': "Chiedi informazioni su funzione, malattia o meccanismo...",
        'ai_welcome': "Ciao! Sono il tuo Assistente Genetico AI. Chiedimi qualsiasi cosa su questo gene!",
        'allele_freq': "Frequenza Allelica (1000 Genomes)",
        'pop_afr': "Africana",
        'pop_amr': "Mista Americana",
        'pop_eas': "Est Asiatica",
        'pop_eur': "Europea",
        'pop_sas': "Sud Asiatica",
        'tab_3d': "🧬 Struttura 3D",
        'tab_mutation': "🧪 Laboratorio Mutazioni",
        'tab_align': "⚔️ Allineamento",
        'pdb_input': "ID PDB (es. 1TRZ)",
        'render_3d': "Renderizza Struttura 3D",
        'mutation_intro': "Modifica la sequenza DNA qui sotto per simulare mutazioni.",
        'simulate_btn': "Esegui Simulazione",
        'original': "Originale",
        'mutated': "Mutato",
        'protein_diff': "Differenze Proteiche",
        'silent_mutation': "Mutazione Silente (Nessun cambio proteina)",
        'stop_codon': "⚠️ Codone di Stop Introdotto!",
        'align_intro': "Confronta due sequenze per trovare somiglianze e mutazioni.",
        'seq1': "Sequenza 1 (Riferimento)",
        'seq2': "Sequenza 2 (Query)",
        'align_btn': "Allinea Sequenze",
        'alignment_score': "Punteggio Allineamento",
        'match_score': "Punteggio Corrispondenza",
        'mismatch_score': "Punteggio Errore",
        'gap_score': "Punteggio Gap",
        'seq_len': "Lunghezza Sequenza",
        'gc_content': "Contenuto GC",
        'base_comp': "Composizione Basi",
        'gc_skew': "Analisi GC Skew",
        'gc_skew_desc': "GC Skew mobile per identificare origini di replicazione o bias.",
        'codon_usage': "Bias Uso Codoni",
        'codon_table': "Vedi Tabella Uso Codoni",
        'kmer_freq': "-mer Analisi Frequenza",
        'no_kmers': "Nessun K-mer trovato.",
        'trans_props': "Traduzione & Proprietà Fisico-chimiche",
        'prot_seq': "Sequenza Proteica",
        'mol_weight': "Peso Mol.",
        'isoelectric': "Punto Isoelettrico (pI)",
        'instability': "Indice Instabilità",
        'aromaticity': "Aromaticità",
        'unstable': "⚠️ Proteina classificata come **instabile** (Indice > 40).",
        'stable': "✅ Proteina classificata come **stabile**.",
        'entropy': "Analisi Entropia",
        'global_entropy': "Entropia Shannon Globale",
        'calc_rolling': "Calcola Entropia Mobile",
        'motif_search': "Ricerca Motivi",
        'find_motif': "Trova Motivo (DNA)",
        'found_matches': "Trovate {} corrispondenze.",
        'not_found': "Non trovato.",
        'error_fetch': "Impossibile recuperare dati per ID:",
        'landing_info': "👈 Seleziona un gene o inserisci un ID Accessione nella barra laterale per iniziare.",
        'features_title': "### Funzionalità",
        'features_list': """
        - **Analisi Proteica**: Peso molecolare, pI e predizione stabilità.
        - **Struttura DNA**: Visualizzazione GC Skew per rilevare origini di replicazione.
        - **Grafici Interattivi**: Grafici zoomabili per K-mers ed entropia.
        """,
        'language_select': "Lingua / Language",
        'disease_map': "Mappa Varianti Malattie",
        'disease_desc': "Varianti patogeniche note mappate sulla sequenza di riferimento (Educativo).",
        'variant': "Variante",
        'disease': "Malattia",
        'significance': "Significatività",
        'position': "Posizione"
    },
    'SK': {
        'title': "🧬 Analýza Ľudského Genómu",
        'subtitle': "_Preskúmajte a analyzujte sekvencie DNA pomocou pokročilých bioinformatických nástrojov._",
        'sidebar_header': "🔍 Výber Génu",
        'search_method': "Metóda Vyhľadávania",
        'search_by_name': "Hľadať podľa Názvu",
        'accession_id': "Prístupové ID",
        'gene_name_placeholder': "napr. inzulín, TP53",
        'results': "Výsledky",
        'no_matches': "Žiadne zhody sa nenašli.",
        'metadata_error': "Metadáta nie sú k dispozícii.",
        'settings_header': "⚙️ Nastavenia Analýzy",
        'kmer_len': "Dĺžka K-mer",
        'window_size': "Posuvné Okno (pb)",
        'analyze_btn': "🚀 Analyzovať Sekvenciu",
        'fetching': "Získavanie údajov sekvencie pre",
        'loaded': "Načítané",
        'description': "Popis",
        'raw_seq': "Surová Sekvencia (Prvých 500pb)",
        'tab_overview': "📊 Prehľad",
        'tab_dna': "🧬 Štruktúra DNA",
        'tab_kmers': "🦠 K-mery",
        'tab_protein': "🥩 Analýza Proteínov",
        'tab_advanced': "🔎 Motívy a Entropia",
        'tab_ai': "💬 AI Asistent",
        'tab_disease': "🏥 Asociácie Chorôb",
        'ai_intro': "Chatujte s AI genetickým asistentom a dozviete sa viac o tomto géne.",
        'ai_placeholder': "Opýtajte sa na funkciu, chorobu alebo mechanizmus...",
        'ai_welcome': "Ahoj! Som tvoj AI genetický asistent. Opýtaj sa ma na čokoľvek o tomto géne!",
        'allele_freq': "Alelová Frekvencia (1000 Genomes)",
        'pop_afr': "Africká",
        'pop_amr': "Zmiešaná Americká",
        'pop_eas': "Východoázijská",
        'pop_eur': "Európska",
        'pop_sas': "Juhoázijská",
        'tab_3d': "🧬 3D Štruktúra",
        'tab_mutation': "🧪 Laboratórium Mutácií",
        'tab_align': "⚔️ Zarovnanie",
        'pdb_input': "PDB ID (napr. 1TRZ)",
        'render_3d': "Vykresliť 3D Štruktúru",
        'mutation_intro': "Upravte DNA sekvenciu nižšie na simuláciu mutácií.",
        'simulate_btn': "Spustiť Simuláciu",
        'original': "Originál",
        'mutated': "Mutovaný",
        'protein_diff': "Rozdiely v Proteínoch",
        'silent_mutation': "Tichá Mutácia (Žiadna zmena proteínu)",
        'stop_codon': "⚠️ Zavedený Stop Kodón!",
        'align_intro': "Porovnajte dve sekvencie na nájdenie podobností a mutácií.",
        'seq1': "Sekvencia 1 (Referencia)",
        'seq2': "Sekvencia 2 (Dopyt)",
        'align_btn': "Zarovnať Sekvencie",
        'alignment_score': "Skóre Zarovnania",
        'match_score': "Skóre Zhody",
        'mismatch_score': "Skóre Nezhody",
        'gap_score': "Skóre Medzery",
        'seq_len': "Dĺžka Sekvencie",
        'gc_content': "Obsah GC",
        'base_comp': "Zloženie Báz",
        'gc_skew': "Analýza GC Skew",
        'gc_skew_desc': "Posuvný GC Skew na identifikáciu počiatkov replikácie alebo skreslenia.",
        'codon_usage': "Zaujatosť Používania Kodónov",
        'codon_table': "Zobraziť Tabuľku Používania Kodónov",
        'kmer_freq': "-mer Analýza Frekvencie",
        'no_kmers': "Nenašli sa žiadne K-mery.",
        'trans_props': "Preklad a Fyzikálno-chemické Vlastnosti",
        'prot_seq': "Proteínová Sekvencia",
        'mol_weight': "Mol. Hmotnosť",
        'isoelectric': "Izoelektrický bod (pI)",
        'instability': "Index Nestability",
        'aromaticity': "Aromaticita",
        'unstable': "⚠️ Proteín je klasifikovaný ako **nestabilný** (Index > 40).",
        'stable': "✅ Proteín je klasifikovaný ako **stabilný**.",
        'entropy': "Analýza Entropie",
        'global_entropy': "Globálna Shannonova Entropia",
        'calc_rolling': "Vypočítať Posuvnú Entropiu",
        'motif_search': "Vyhľadávanie Motívov",
        'find_motif': "Nájsť Motív (DNA)",
        'found_matches': "Nájdené {} zhody.",
        'not_found': "Nenašlo sa.",
        'error_fetch': "Nepodarilo sa získať údaje pre ID:",
        'landing_info': "👈 Na začatie vyberte gén alebo zadajte prístupové ID v bočnom paneli.",
        'features_title': "### Funkcie",
        'features_list': """
        - **Analýza Proteínov**: Molekulová hmotnosť, pI a predpoveď stability.
        - **Štruktúra DNA**: Vizualizácia GC Skew na detekciu počiatkov replikácie.
        - **Interaktívne Grafy**: Priblížiteľné grafy pre K-mery a entropiu.
        """,
        'language_select': "Jazyk / Language",
        'disease_map': "Mapa Variantov Chorôb",
        'disease_desc': "Známe patogénne varianty mapované na referenčnú sekvenciu (Vzdelávacie).",
        'variant': "Variant",
        'disease': "Choroba",
        'significance': "Významnosť",
        'position': "Pozícia"
    }
}
